# Generated by Django 4.0.2 on 2022-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.TextField()),
                ('student_age', models.TextField()),
                ('student_cccd', models.TextField()),
                ('student_email', models.TextField()),
                ('student_sex', models.TextField()),
                ('student_class', models.TextField()),
                ('student_address', models.TextField()),
                ('student_img', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
